create user camping identified by 1234;
grant connect, resource, create view to camping;

DROP TABLE "ATTACH" CASCADE CONSTRAINTS;
DROP TABLE "REPLY" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_AUTH" CASCADE CONSTRAINTS;
DROP TABLE "RESERVE" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "CAMP" CASCADE CONSTRAINTS;

CREATE TABLE "CAMP" (
	"CAMP_NO"	VARCHAR2(10)		NOT NULL,
	"CAMP_PRICE"	NUMBER(10)		NOT NULL,
	"CAMP_CATEGORY"	VARCHAR2(20)		NOT NULL,
	"CAMP_SIZE"	VARCHAR2(10)		NULL,
	"CAMP_CAPACITY"	NUMBER(2)	DEFAULT 0	NOT NULL
);

CREATE TABLE "BOARD_REVIEW" (
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATEDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_HIT"	NUMBER(10)	DEFAULT 0	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PW"	VARCHAR2(100)		NOT NULL,
	"MEM_NAME"	VARCHAR2(10)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(30)		NOT NULL,
	"MEM_TEL"	VARCHAR2(20)		NOT NULL,
	"MEM_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "RESERVE" (
	"RESERVE_NO"	NUMBER(10)		NOT NULL,
	"RESERVE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RESERVE_PEOPLE"	NUMBER(2)		NOT NULL,
	"CAMP_NO"	VARCHAR2(10)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "MEMBER_AUTH" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"AUTH"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER(10)		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPLY_UPDATEDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "ATTACH" (
	"ATTACH_UUID"	VARCHAR2(100)		NOT NULL,
	"ATTACH_PATH"	VARCHAR2(200)		NOT NULL,
	"ATTACH_NAME"	VARCHAR2(100)		NOT NULL,
	"BOARD_NO"	NUMBER(10)		NOT NULL
);

CREATE TABLE "BOARD_NOTICE" (
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATEDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_HIT"	NUMBER(10)	DEFAULT 0	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "BOARD_INQUIRY" (
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATEDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_HIT"	NUMBER(10)	DEFAULT 0	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

ALTER TABLE "CAMP" ADD CONSTRAINT "PK_CAMP" PRIMARY KEY (
	"CAMP_NO"
);

ALTER TABLE "BOARD_REVIEW" ADD CONSTRAINT "PK_BOARD_REVIEW" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "PK_RESERVE" PRIMARY KEY (
	"RESERVE_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY (
	"ATTACH_UUID"
);

ALTER TABLE "BOARD_NOTICE" ADD CONSTRAINT "PK_BOARD_NOTICE" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_INQUIRY" ADD CONSTRAINT "PK_BOARD_INQUIRY" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REVIEW_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_CAMP_TO_RESERVE_1" FOREIGN KEY (
	"CAMP_NO"
)
REFERENCES "CAMP" (
	"CAMP_NO"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_MEMBER_TO_RESERVE_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "MEMBER_AUTH" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_AUTH_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_REVIEW_TO_REPLY_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD_REVIEW" (
	"BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "FK_BOARD_REVIEW_TO_ATTACH_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD_REVIEW" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_NOTICE_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_INQUIRY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

DROP TABLE BOARD_NOTICE CASCADE CONSTRAINTS;
DROP TABLE ATTACH CASCADE CONSTRAINTS;
DROP TABLE BOARD_REVIEW CASCADE CONSTRAINTS;
DROP TABLE RESERVE CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE CAMP CASCADE CONSTRAINTS;
DROP TABLE MEMBER_AUTH CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD_INQUIRY CASCADE CONSTRAINTS;

CREATE TABLE "CAMP" (
   "CAMP_NO"   VARCHAR2(10)      NOT NULL,
   "CAMP_PRICE"   NUMBER(10)      NOT NULL,
   "CAMP_PEAKPRICE"   NUMBER(10)      NOT NULL,
   "CAMP_CATEGORY"   VARCHAR2(20)      NOT NULL,
   "CAMP_SIZE"   VARCHAR2(10)      NULL,
   "CAMP_CAPACITY"   NUMBER(2)   DEFAULT 0   NOT NULL
);

CREATE TABLE "BOARD_REVIEW" (
   "BOARD_NO"   NUMBER(10)      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(100)      NOT NULL,
   "BOARD_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "BOARD_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_UPDATEDATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_HIT"   NUMBER(10)   DEFAULT 0   NOT NULL,
   "MEM_ID"   VARCHAR2(20)      NOT NULL
);

CREATE TABLE "MEMBER" (
   "MEM_ID"   VARCHAR2(20)      NOT NULL,
   "MEM_PW"   VARCHAR2(100)      NOT NULL,
   "MEM_NAME"   VARCHAR2(20)      NOT NULL,
   "MEM_EMAIL"   VARCHAR2(30)      NOT NULL,
   "MEM_TEL"   VARCHAR2(20)      NOT NULL,
   "MEM_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "MEM_ENABLED"   CHAR(1)   DEFAULT 1   NOT NULL
);

CREATE TABLE "RESERVE" (
   "RESERVE_NO"   NUMBER(10)      NOT NULL,
   "RESERVE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "RESERVE_PEOPLE"   NUMBER(2)      NOT NULL,
   "RESERVE_PRICE"   NUMBER(10)      NOT NULL,
   "CAMP_NO"   VARCHAR2(10)      NOT NULL,
   "MEM_ID"   VARCHAR2(20)      NOT NULL
);

CREATE TABLE "MEMBER_AUTH" (
   "MEM_ID"   VARCHAR2(20)      NOT NULL,
   "AUTH"   VARCHAR2(50)      NOT NULL
);

CREATE TABLE "REPLY" (
   "REPLY_NO"   NUMBER(10)      NOT NULL,
   "REPLY_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "REPLY_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "REPLY_UPDATEDATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_NO"   NUMBER(10)      NOT NULL,
   "MEM_ID"   VARCHAR2(20)      NOT NULL
);

CREATE TABLE "ATTACH" (
   "ATTACH_UUID"   VARCHAR2(100)      NOT NULL,
   "ATTACH_PATH"   VARCHAR2(200)      NOT NULL,
   "ATTACH_NAME"   VARCHAR2(100)      NOT NULL,
   "BOARD_NO"   NUMBER(10)      NOT NULL
);

CREATE TABLE "BOARD_NOTICE" (
   "BOARD_NO"   NUMBER(10)      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(100)      NOT NULL,
   "BOARD_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "BOARD_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_UPDATEDATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_HIT"   NUMBER(10)   DEFAULT 0   NOT NULL,
   "MEM_ID"   VARCHAR2(20)      NOT NULL
);

CREATE TABLE "BOARD_INQUIRY" (
   "BOARD_NO"   NUMBER(10)      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(100)      NOT NULL,
   "BOARD_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "BOARD_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_UPDATEDATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_HIT"   NUMBER(10)   DEFAULT 0   NOT NULL,
   "MEM_ID"   VARCHAR2(20)      NOT NULL
);

ALTER TABLE "CAMP" ADD CONSTRAINT "PK_CAMP" PRIMARY KEY (
   "CAMP_NO"
);

ALTER TABLE "BOARD_REVIEW" ADD CONSTRAINT "PK_BOARD_REVIEW" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
   "MEM_ID"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "PK_RESERVE" PRIMARY KEY (
   "RESERVE_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
   "REPLY_NO"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY (
   "ATTACH_UUID"
);

ALTER TABLE "BOARD_NOTICE" ADD CONSTRAINT "PK_BOARD_NOTICE" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "BOARD_INQUIRY" ADD CONSTRAINT "PK_BOARD_INQUIRY" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "BOARD_REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REVIEW_1" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "MEMBER" (
   "MEM_ID"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_CAMP_TO_RESERVE_1" FOREIGN KEY (
   "CAMP_NO"
)
REFERENCES "CAMP" (
   "CAMP_NO"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_MEMBER_TO_RESERVE_1" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "MEMBER" (
   "MEM_ID"
);

ALTER TABLE "MEMBER_AUTH" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_AUTH_1" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "MEMBER" (
   "MEM_ID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_REVIEW_TO_REPLY_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD_REVIEW" (
   "BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "MEMBER" (
   "MEM_ID"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "FK_BOARD_REVIEW_TO_ATTACH_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD_REVIEW" (
   "BOARD_NO"
);

ALTER TABLE "BOARD_NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_NOTICE_1" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "MEMBER" (
   "MEM_ID"
);

CREATE SEQUENCE board_no
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

drop SEQUENCE board_no;

select board_no.nextval from dual
select * from BOARD_INQUIRY;
select * from member;

INSERT INTO "MEMBER" ("MEM_ID", "MEM_PW", "MEM_NAME", "MEM_EMAIL", "MEM_TEL", "MEM_DATE", "MEM_ENABLED") VALUES ('user1', 'password1', 'John Doe', 'john@example.com', '123456789', SYSDATE, '1');
INSERT INTO "MEMBER" ("MEM_ID", "MEM_PW", "MEM_NAME", "MEM_EMAIL", "MEM_TEL", "MEM_DATE", "MEM_ENABLED") VALUES ('user2', 'password2', 'Jane Smith', 'jane@example.com', '987654321', SYSDATE, '1');
INSERT INTO "MEMBER" ("MEM_ID", "MEM_PW", "MEM_NAME", "MEM_EMAIL", "MEM_TEL", "MEM_DATE", "MEM_ENABLED") VALUES ('user3', 'password3', 'Michael Johnson', 'michael@example.com', '555555555', SYSDATE, '1');
INSERT INTO "MEMBER" ("MEM_ID", "MEM_PW", "MEM_NAME", "MEM_EMAIL", "MEM_TEL", "MEM_DATE", "MEM_ENABLED") VALUES ('user4', 'password4', 'Emily Brown', 'emily@example.com', '111111111', SYSDATE, '1');
INSERT INTO "MEMBER" ("MEM_ID", "MEM_PW", "MEM_NAME", "MEM_EMAIL", "MEM_TEL", "MEM_DATE", "MEM_ENABLED") VALUES ('user5', 'password5', 'William Wilson', 'william@example.com', '999999999', SYSDATE, '1');

select * from member;

INSERT INTO "BOARD_INQUIRY" ("BOARD_NO", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_DATE", "BOARD_UPDATEDATE", "BOARD_HIT", "MEM_ID") VALUES (1, 'First Inquiry', 'This is the first inquiry content.', SYSDATE, SYSDATE, 0, 'user1');
INSERT INTO "BOARD_INQUIRY" ("BOARD_NO", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_DATE", "BOARD_UPDATEDATE", "BOARD_HIT", "MEM_ID") VALUES (2, 'Second Inquiry', 'This is the second inquiry content.', SYSDATE, SYSDATE, 0, 'user2');
INSERT INTO "BOARD_INQUIRY" ("BOARD_NO", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_DATE", "BOARD_UPDATEDATE", "BOARD_HIT", "MEM_ID") VALUES (3, 'Third Inquiry', 'This is the third inquiry content.', SYSDATE, SYSDATE, 0, 'user3');
INSERT INTO "BOARD_INQUIRY" ("BOARD_NO", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_DATE", "BOARD_UPDATEDATE", "BOARD_HIT", "MEM_ID") VALUES (4, 'Fourth Inquiry', 'This is the fourth inquiry content.', SYSDATE, SYSDATE, 0, 'user4');
INSERT INTO "BOARD_INQUIRY" ("BOARD_NO", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_DATE", "BOARD_UPDATEDATE", "BOARD_HIT", "MEM_ID") VALUES (5, 'Fifth Inquiry', 'This is the fifth inquiry content.', SYSDATE, SYSDATE, 0, 'user5');

select * from BOARD_INQUIRY;